services:
  main:
    # container_name: main
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/usr/src/app/node_modules

    user: '1000:1000'

    working_dir: /app
    command: sleep infinity

    # ports:
      # - ${SERVER_PORT}:${SERVER_PORT}


volumes:
  node_modules:
