name: carousell-3d-print-position-check
on:
  push:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  carousell-3d-print-position-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        uses: cypress-io/github-action@v4
        # the parameters below are only necessary
        # because we are running these examples in a monorepo
        with:
          working-directory: carousell-3d-print-position-check
          # just for full picture after installing Cypress
          # print information about detected browsers, etc
          # see https://on.cypress.io/command-line#cypress-info
          build: npm run build
          start: npm start

      # carousell-3d-print-position-check-on-windows:
      #   runs-on: windows-latest
      #   steps:
      #     - name: Checkout
      #       uses: actions/checkout@v2

      #     - name: Cypress tests
      #       uses: cypress-io/github-action@v2
      #       with:
      #         working-directory: carousell-3d-print-position-check
      #         build: npx cypress run

      - uses: actions/upload-artifact@v2
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: carousell-3d-print-position-check_screenshots
          path: |
            carousell-3d-print-position-check/cypress/screenshots
        if: failure()
