name: cypress-helloworld-tryout
on:
  push:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  cypress-helloworld-tryout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: run test
        run: |
          cd cypress-helloworld-tryout
            npm i
            npm run test
          cd ..

      - name: run test using chrome
        run: |
          cd cypress-helloworld-tryout
            npm i
            npm run test_chrome
          cd ..

      - name: run test using test_electron
        run: |
          cd cypress-helloworld-tryout
            npm i
            npm run test_electron
          cd ..

      - name: upload artifact if failure
        uses: actions/upload-artifact@v2
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: cypress-helloworld-tryout-artifacts
          path: |
            cypress-helloworld-tryout/cypress/screenshots
            cypress-helloworld-tryout/cypress/videos
        if: failure()

      - uses: craftech-io/slack-action@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack_channel: site_status
          slack_username: Github
          status: failure
        if: failure()
