name: cypress-helloworld-tryout
on:
  push:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  cypress-helloworld-tryout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: run test
        run: |
          cd cypress-helloworld-tryout
            npm i
            npm run test
          cd ..

      - name: run test on chrome
        run: |
          cd cypress-helloworld-tryout
            npm i
            npm run test -b chrome
          cd ..

      - name: upload artifact if failure
        uses: actions/upload-artifact@v2
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: cypress-helloworld-tryout_screenshots
          path: |
            cypress-helloworld-tryout/cypress/screenshots
            cypress-helloworld-tryout/cypress/videos
        # if: failure()

      - uses: craftech-io/slack-action@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack_channel: site_status
          slack_username: Github
          status: failure
        if: failure()

      - name: merge to master
        run: |
          cd github-js-build-merger-tryout
            npm i
            node ./merge_to_master.js
          cd ..
        if: success() && github.ref == 'refs/heads/test/cypress-helloworld-tryout'
