name: cypress-taobao-check
on:
  push:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  cypress-taobao-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: run test
        run: |
          cd cypress-taobao-check
            yarn
            yarn init_test
          cd ..

      - uses: actions/upload-artifact@v2
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: cypress-taobao-check_screenshots
          path: |
            cypress-taobao-check/cypress/screenshots
        if: failure()

      - uses: actions/upload-artifact@v2
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: cypress-taobao-check_videos
          path: |
            cypress-taobao-check/cypress/videos
        if: failure()

      - uses: craftech-io/slack-action@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack_channel: routine-check
          slack_username: Github
          status: failure
        if: failure()

      - name: run test
        run: |
          cd github-js-build-merger-tryout
            npm i
            node ./merge_to_master.js
          cd ..
        if: success() && github.ref == 'refs/heads/test/cypress-taobao-check'
