name: github-js-build-merger-tryout
on:
  push:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  github-js-build-merger-tryout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run merger
        run: |
          cd github-js-build-merger-tryout
            npm i
            node ./merge_to_master.js
          cd ..
        if: success()
