name: louislabs-traefik-check
on:
  push:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  louislabs-traefik-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: run test
        run: |
          cd louislabs-traefik-check
            yarn
            yarn test
          cd ..

      - uses: craftech-io/slack-action@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack_channel: routine-check
          slack_username: Github
          status: failure
        if: failure()

      # - name: merge to master
      #   run: |
      #     cd github-js-build-merger-tryout
      #       npm i
      #       node ./merge_to_master.js
      #     cd ..
      #   if: success() && github.ref == 'refs/heads/test/louislabs-traefik-check'
