name: status-iamon99-com-check
on:
  push:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  status-iamon99-com-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run test
        run: |
          cd status-iamon99-com-check
            yarn
            yarn init_test
          cd ..

      - uses: actions/upload-artifact@v2
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: status-iamon99-com-check_screenshots
          path: |
            status-iamon99-com-check/cypress/screenshots
        if: failure()

      - uses: actions/upload-artifact@v2
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: status-iamon99-com-check_videos
          path: |
            status-iamon99-com-check/cypress/videos
        if: failure()

      - uses: craftech-io/slack-action@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack_channel: site_status
          slack_username: Github
          status: failure
        if: failure()

      - name: run test
        run: |
          cd github-js-build-merger-tryout
            npm i
            node ./merge_to_master.js
          cd ..
        if: success()
